@startuml deployment

'left to right direction

'skinparam linetype ortho
skinparam linetype polyline

skinparam nodesep 25
skinparam ranksep 20


node Server {
    frame Docker {
        rectangle frontend {
            component nginx {

            }
            folder static {

            }
        }

        rectangle backend {
            component api_server [fastapi 
            application]
        }

        queue queue {

        }

        rectangle notifications {

        }

        rectangle database {
            database postgres
        }

        rectangle "blob storage" as blob {
            database minio
        }
    }
}



node Android as andoid {
    component Chrome {

    }
}

node IOS as ios {
    component Safari {

    }
}




nginx -l-> api_server : /api
nginx -r-> static : /index.html

nginx -d-> minio : /media


api_server --> postgres
api_server <--> queue

notifications <--> queue
notifications --> postgres

Safari --> nginx : https

Chrome --> nginx : https

@enduml