@startuml sample_diagram

node Server {
    frame Docker {
        rectangle frontend {

        }

        rectangle backend {

        }

        rectangle database {
            
        }
    }
}



@enduml