@startuml packages

left to right direction

folder models {
    file User
    file Media
    file Message
    file Rating
    file Chat
}

folder usecases {
    file register_user
    file get_user
    file update_profile
    file update_avatar
    file friends
    file ratings
    file chats
}

folder repositories {
    file user_repository
    file media_repository
    file friendship_repository
    file rating_repository
    file chat_repository
}

folder external {
    file notifications_service
}

folder impl {
    file postgres_repo_impl
    file minio_media_repository
    file "notifications_service" as NotificationsServiceImpl
}

@enduml