name: Generate PlantUML Diagrams
on:
  push:
    paths:
      - "**.puml"
    branches:
      - master
jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      UML_FILES: ".puml"
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get changed UML files
        id: getfile
        run: |
          find *.puml \
          | awk -F' ' '{
                      # only process puml files
                      # do not try to process our theme or custom config
                      if ( $1 ~ /\.puml$/ && $1 !~ /(theme|config)\.puml$/ )
                      {
                        # only print the file name and strip newlines for spaces
                        printf "%s ", $1
                      }
                    }
                    END { print "" } # ensure we do print a newline at the end
                    ' \
          | awk '{printf "::set-output name=files::" "%s ", $0}'
      - name: UML files considered echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - name: Generate SVG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
          args: -v -tsvg ${{ steps.getfile.outputs.files }}
      - name: Generate PNG Diagrams
        uses: cloudbees/plantuml-github-action@master
        with:
          args: -v -tpng ${{ steps.getfile.outputs.files }}
      - name: Push Local Changes
        uses: stefanzweifel/git-auto-commit-action@v4.1.2
        with:
          commit_user_name: "Vladimir Redkin"
          commit_user_email: "vsredkin01@gmail.com"
          commit_author: "Vladimir Redkin <vsredkin01@gmail.com>"
          commit_message: "Generate SVG and PNG images for PlantUML diagrams"
          branch: ${{ github.head_ref }}
